services:
  - type: web
    name: tes-insurance-backend
    env: node
    plan: free
    buildCommand: chmod +x build-debug.sh && ./build-debug.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: /opt/render/project/backend/data/insurance.db
      - key: CORS_ORIGIN
        value: https://tes-insurance-agency.vercel.app,https://tesinsurance.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
    healthCheckPath: /health
    autoDeploy: true
    branch: main
